/**
 * Represents a high-level instruction for the camera-controls library.
 * These instructions are generated by the backend SceneInterpreter
 * and consumed by the frontend AnimationController.
 */
export interface ControlInstruction {
  /**
   * The method name on the camera-controls instance to call.
   * E.g., 'dollyTo', 'rotateTo', 'setLookAt', 'truck', 'zoomTo', 'moveTo', 'setPosition', 'setTarget'.
   */
  method: string;

  /**
   * An array of arguments to pass to the specified method.
   * The types and number of arguments depend on the method.
   * E.g., for 'dollyTo': [distance: number, enableTransition: boolean]
   * E.g., for 'rotateTo': [azimuthAngle: number, polarAngle: number, enableTransition: boolean]
   */
  args: any[]; // Using any[] for now, can be refined with specific types per method if feasible later
}

// Example Usage (for reference, not part of the file):
// const instructions: ControlInstruction[] = [
//   { method: 'dollyTo', args: [5, true] },
//   { method: 'rotateTo', args: [Math.PI / 2, Math.PI / 4, true] },
//   { method: 'setLookAt', args: [0, 10, 0, 0, 0, 0, true] }
// ]; 